spring.application.name=online-gem-buy-sell-system
server.port=8080

# choose profile (mysql when using DB)
spring.profiles.active=mysql

app.upload.dir=uploads
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB