spring.application.name=gemtrade-marketplace

# Database Connection
spring.datasource.url=jdbc:mysql://localhost:3306/gemtrade_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Dil@617!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# Flyway (Matches your V1__init.sql location)
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Serving Static Content (HTML/JS/Images)
spring.web.resources.static-locations=classpath:/static/